import { PlacePOI } from "../../types/superApp";

export const OCEAN_PARK_1_BOUNDARY: [number, number][] = [
  [21.0047847, 105.9477604],
  [20.9933962, 105.9628773],
  [20.9890436, 105.9600712],
  [20.9852230, 105.9518985],
  [20.9840728, 105.9509930],
  [20.9851752, 105.9432602],
  [20.9921545, 105.9371584],
  [20.9968500, 105.9334673],
  [20.9980664, 105.9352872],
  [21.0017814, 105.9420739],
];

export const MAP_OUTER_MASK: [number, number][] = [
  [85, -180],
  [85, 180],
  [-85, 180],
  [-85, -180],
];

export const MAP_CENTER_OCEAN_PARK: [number, number] = [20.9942, 105.9485];
export const USER_DEFAULT_LOCATION: [number, number] = [20.9930, 105.9460];

export const OCEAN_PARK_POIS: PlacePOI[] = [
  {
    id: "poi-vinuni",
    name: "Khuôn viên VinUniversity",
    category: "university",
    subdivision: "Phía Tây Nam",
    latitude: 20.9898,
    longitude: 105.9467,
    description: "Trường đại học tinh hoa với khuôn viên xanh rộng lớn, cây cối rợp bóng và hồ cảnh quan trong lành.",
    estimatedAqi: 42,
    sensorIdRef: "S04",
    bestTimeToVisit: "06:30 – 17:30",
    iconName: "GraduationCap",
  },
  {
    id: "poi-ngoc-trai-lake",
    name: "Hồ Ngọc Trai (Hồ nước ngọt 24.5ha)",
    category: "lake",
    subdivision: "Trung tâm",
    latitude: 20.9953,
    longitude: 105.9500,
    description: "Trái tim của Ocean Park 1 với bờ cát trắng trải dài, hàng dừa xanh và không gian lộng gió.",
    estimatedAqi: 158,
    sensorIdRef: "S03",
    bestTimeToVisit: "Sau 19:30 khi mật độ xe giảm",
    iconName: "Waves",
  },
  {
    id: "poi-salt-lake",
    name: "Biển Hồ Nước Mặn Crystal Lagoons",
    category: "lake",
    subdivision: "Phía Đông",
    latitude: 20.9945,
    longitude: 105.9585,
    description: "Biển hồ nước mặn nhân tạo 6.1ha mang làn nước trong xanh nhiệt đới ngay giữa lòng đại đô thị.",
    estimatedAqi: 75,
    sensorIdRef: "S05",
    bestTimeToVisit: "07:00 – 10:00",
    iconName: "Sun",
  },
  {
    id: "poi-sapphire",
    name: "Khu Căn hộ Sapphire (S1 & S2)",
    category: "residential",
    subdivision: "Phía Tây Bắc",
    latitude: 20.9975,
    longitude: 105.9430,
    description: "Cụm căn hộ hiện đại mật độ cao, sôi động với nhiều tiện ích thể thao và shophouse khối đế.",
    estimatedAqi: 72,
    sensorIdRef: "S02",
    bestTimeToVisit: "Cả ngày",
    iconName: "Building2",
  },
  {
    id: "poi-ruby-zenpark",
    name: "Phân khu Ruby & The Zenpark",
    category: "residential",
    subdivision: "Phía Tây",
    latitude: 20.9935,
    longitude: 105.9405,
    description: "Căn hộ phong cách Nhật Bản với vườn thiền Zenpark, hồ cá Koi và đồi tùng thanh tịnh.",
    estimatedAqi: 48,
    sensorIdRef: "S02",
    bestTimeToVisit: "06:00 – 08:30",
    iconName: "Trees",
  },
  {
    id: "poi-hai-au",
    name: "Khu Biệt thự Hải Âu",
    category: "residential",
    subdivision: "Phía Đông Nam",
    latitude: 20.9910,
    longitude: 105.9560,
    description: "Khu biệt thự thương mại ven biển hồ, không gian thoáng đãng dọc đại lộ 52m.",
    estimatedAqi: 65,
    sensorIdRef: "S05",
    bestTimeToVisit: "Buổi sáng sớm",
    iconName: "Home",
  },
  {
    id: "poi-coral-park",
    name: "Công viên San Hô (Coral Park)",
    category: "park",
    subdivision: "Phía Nam",
    latitude: 20.9870,
    longitude: 105.9490,
    description: "Công viên sinh thái ven sông với thảm cỏ nướng BBQ, đường dạo bộ và vườn nướng dã ngoại.",
    estimatedAqi: 38,
    sensorIdRef: "S04",
    bestTimeToVisit: "15:30 – 18:00",
    iconName: "Flower2",
  },
  {
    id: "poi-vincom",
    name: "Vincom Mega Mall Ocean Park",
    category: "mall",
    subdivision: "Phía Đông",
    latitude: 20.9960,
    longitude: 105.9575,
    description: "Trung tâm thương mại biển đầu tiên tại Hà Nội với hàng trăm gian hàng mua sắm, ẩm thực và rạp chiếu phim.",
    estimatedAqi: 82,
    sensorIdRef: "S05",
    bestTimeToVisit: "10:00 – 21:00",
    iconName: "ShoppingBag",
  },
  {
    id: "poi-technopark",
    name: "Tòa tháp thông minh TechnoPark Tower",
    category: "landmark",
    subdivision: "Cửa ngõ Tây Nam",
    latitude: 20.9885,
    longitude: 105.9420,
    description: "Tòa tháp văn phòng thông minh Top 10 thế giới đạt chứng chỉ xanh LEED Platinum.",
    estimatedAqi: 45,
    sensorIdRef: "S04",
    bestTimeToVisit: "Giờ hành chính",
    iconName: "Building",
  },
  {
    id: "poi-gate-1",
    name: "Cổng Chào Số 1 (Trục Đa Tốn)",
    category: "gate",
    subdivision: "Cửa ngõ Tây Bắc",
    latitude: 21.0008,
    longitude: 105.9428,
    description: "Cửa ngõ kết nối Ocean Park 1 với đường Đa Tốn và Quốc lộ 5B.",
    estimatedAqi: 118,
    sensorIdRef: "S01",
    bestTimeToVisit: "Tránh giờ cao điểm",
    iconName: "Compass",
  },
];
