import { PlacePOI } from "../../types/superApp";

export const OCEAN_PARK_1_BOUNDARY: [number, number][] = [
  [21.0047847, 105.9477604],
  [20.9933962, 105.9628773],
  [20.9890436, 105.9600712],
  [20.9852230, 105.9518985],
  [20.9840728, 105.9509930],
  [20.9851752, 105.9432602],
  [20.9921545, 105.9371584],
  [20.9968500, 105.9334673],
  [20.9980664, 105.9352872],
  [21.0017814, 105.9420739],
];

export const MAP_OUTER_MASK: [number, number][] = [
  [85, -180],
  [85, 180],
  [-85, 180],
  [-85, -180],
];

export const MAP_CENTER_OCEAN_PARK: [number, number] = [20.9942, 105.9485];
export const USER_DEFAULT_LOCATION: [number, number] = [20.9930, 105.9460];

export const OCEAN_PARK_POIS: PlacePOI[] = [
  {
    id: "poi-vinuni",
    name: "Khuôn viên VinUniversity",
    category: "university",
    subdivision: "Phía Tây Nam",
    latitude: 20.9898,
    longitude: 105.9467,
    description: "Trường đại học tinh hoa với khuôn viên xanh rộng lớn, cây cối rợp bóng và hồ cảnh quan trong lành.",
    sensorIdRef: "S04",
    iconName: "GraduationCap",
  },
  {
    id: "poi-ngoc-trai-lake",
    name: "Hồ Ngọc Trai (Hồ nước ngọt 24.5ha)",
    category: "lake",
    subdivision: "Trung tâm",
    latitude: 20.9953,
    longitude: 105.9500,
    description: "Trái tim của Ocean Park 1 với bờ cát trắng trải dài, hàng dừa xanh và không gian lộng gió.",
    sensorIdRef: "S03",
    iconName: "Waves",
  },
  {
    id: "poi-salt-lake",
    name: "Biển Hồ Nước Mặn Crystal Lagoons",
    category: "lake",
    subdivision: "Phía Đông",
    latitude: 20.9945,
    longitude: 105.9585,
    description: "Biển hồ nước mặn nhân tạo 6.1ha mang làn nước trong xanh nhiệt đới ngay giữa lòng đại đô thị.",
    sensorIdRef: "S05",
    iconName: "Sun",
  },
  {
    id: "poi-sapphire",
    name: "Khu Căn hộ Sapphire (S1 & S2)",
    category: "residential",
    subdivision: "Phía Tây Bắc",
    latitude: 20.9975,
    longitude: 105.9430,
    description: "Cụm căn hộ hiện đại mật độ cao, sôi động với nhiều tiện ích thể thao và shophouse khối đế.",
    sensorIdRef: "S02",
    iconName: "Building2",
  },
  {
    id: "poi-ruby-zenpark",
    name: "Phân khu Ruby & The Zenpark",
    category: "residential",
    subdivision: "Phía Tây",
    latitude: 20.9935,
    longitude: 105.9405,
    description: "Căn hộ phong cách Nhật Bản với vườn thiền Zenpark, hồ cá Koi và đồi tùng thanh tịnh.",
    sensorIdRef: "S02",
    iconName: "Trees",
  },
  {
    id: "poi-hai-au",
    name: "Khu Biệt thự Hải Âu",
    category: "residential",
    subdivision: "Phía Đông Nam",
    latitude: 20.9910,
    longitude: 105.9560,
    description: "Khu biệt thự thương mại ven biển hồ, không gian thoáng đãng dọc đại lộ 52m.",
    sensorIdRef: "S05",
    iconName: "Home",
  },
  {
    id: "poi-coral-park",
    name: "Công viên San Hô (Coral Park)",
    category: "park",
    subdivision: "Phía Nam",
    latitude: 20.9870,
    longitude: 105.9490,
    description: "Công viên sinh thái ven sông với thảm cỏ nướng BBQ, đường dạo bộ và vườn nướng dã ngoại.",
    sensorIdRef: "S04",
    iconName: "Flower2",
  },
  {
    id: "poi-vincom",
    name: "Vincom Mega Mall Ocean Park",
    category: "mall",
    subdivision: "Phía Đông",
    latitude: 20.9960,
    longitude: 105.9575,
    description: "Trung tâm thương mại biển đầu tiên tại Hà Nội với hàng trăm gian hàng mua sắm, ẩm thực và rạp chiếu phim.",
    sensorIdRef: "S05",
    iconName: "ShoppingBag",
  },
  {
    id: "poi-technopark",
    name: "Tòa tháp thông minh TechnoPark Tower",
    category: "landmark",
    subdivision: "Cửa ngõ Tây Nam",
    latitude: 20.9885,
    longitude: 105.9420,
    description: "Tòa tháp văn phòng thông minh Top 10 thế giới đạt chứng chỉ xanh LEED Platinum.",
    sensorIdRef: "S04",
    iconName: "Building",
  },
  {
    id: "poi-gate-1",
    name: "Cổng Chào Số 1 (Trục Đa Tốn)",
    category: "gate",
    subdivision: "Cửa ngõ Tây Bắc",
    latitude: 21.0008,
    longitude: 105.9428,
    description: "Cửa ngõ kết nối Ocean Park 1 với đường Đa Tốn và Quốc lộ 5B.",
    sensorIdRef: "S01",
    iconName: "Compass",
  },
  // --- Phòng tập trong nhà & Thể thao điều hòa ---
  {
    id: "poi-vinuni-sports",
    name: "Trung tâm Thể thao & Bể bơi trong nhà VinUni",
    category: "indoor_fitness",
    subdivision: "Phía Tây Nam",
    latitude: 20.9892,
    longitude: 105.9475,
    description: "Nhà thi đấu đa năng điều hòa lọc khí tươi HEPA và cụm bể bơi tiêu chuẩn Olympic.",
    sensorIdRef: "S04",
    iconName: "Dumbbell",
  },
  {
    id: "poi-sapphire-pool",
    name: "Bể bơi 4 mùa Mái kính Sapphire Rooftop",
    category: "pool",
    subdivision: "Phía Tây Bắc (Tòa S2.05)",
    latitude: 20.9980,
    longitude: 105.9435,
    description: "Bể bơi 4 mùa nước ấm trong nhà mái kính panorama, không lo khói bụi và thời tiết.",
    sensorIdRef: "S02",
    iconName: "Waves",
  },
  {
    id: "poi-vincom-fitness",
    name: "Trung tâm Thể hình & Yoga Vincom Mega Mall",
    category: "gym",
    subdivision: "Phía Đông (Tầng 3 Vincom)",
    latitude: 20.9965,
    longitude: 105.9572,
    description: "Phòng tập Gym & Yoga điều hòa cao cấp nhìn thẳng ra biển hồ Crystal Lagoons.",
    sensorIdRef: "S05",
    iconName: "Activity",
  },
  {
    id: "poi-zenpark-clubhouse",
    name: "Nhà Sinh hoạt Thể thao Trong nhà The Zenpark",
    category: "indoor_fitness",
    subdivision: "Phía Tây (Tòa R1.02)",
    latitude: 20.9940,
    longitude: 105.9398,
    description: "Khu tập thể thao trong nhà, bóng bàn, bida và yoga điều hòa riêng cho cư dân Zenpark.",
    sensorIdRef: "S02",
    iconName: "Home",
  },
  // --- Trạm xe buýt điện VinBus ---
  {
    id: "poi-bus-megamall",
    name: "Điểm đón xe bus điện VinBus - Vincom Mega Mall",
    category: "bus",
    subdivision: "Phía Đông",
    latitude: 20.9970,
    longitude: 105.9565,
    description: "Trạm trung chuyển xe bus điện VinBus kết nối các tuyến E01, E02, E03 và nội khu OCP01.",
    sensorIdRef: "S05",
    iconName: "Bus",
  },
  {
    id: "poi-bus-technopark",
    name: "Trạm xe bus điện VinBus - Tòa tháp TechnoPark",
    category: "bus",
    subdivision: "Cửa ngõ Tây Nam",
    latitude: 20.9880,
    longitude: 105.9425,
    description: "Trạm đón trả xe buýt điện thông minh trước sảnh tòa tháp văn phòng TechnoPark.",
    sensorIdRef: "S04",
    iconName: "Bus",
  },
  {
    id: "poi-bus-vinuni",
    name: "Trạm xe bus điện VinBus - Cổng chính VinUniversity",
    category: "bus",
    subdivision: "Phía Tây Nam",
    latitude: 20.9905,
    longitude: 105.9460,
    description: "Điểm dừng xe bus điện phục vụ sinh viên, giảng viên và khách tham quan đại học VinUni.",
    sensorIdRef: "S04",
    iconName: "Bus",
  },
  {
    id: "poi-bus-sapphire",
    name: "Trạm xe bus điện VinBus - Phân khu Sapphire 2",
    category: "bus",
    subdivision: "Phía Tây Bắc",
    latitude: 20.9982,
    longitude: 105.9442,
    description: "Trạm xe bus điện kết nối cụm tòa căn hộ Sapphire 1 & Sapphire 2.",
    sensorIdRef: "S02",
    iconName: "Bus",
  },
  // --- Trạm mượn xe đạp công cộng thông minh (TNGo) ---
  {
    id: "poi-bike-ngoc-trai",
    name: "Trạm mượn xe đạp công cộng - Biển Hồ Ngọc Trai",
    category: "bike",
    subdivision: "Trung tâm",
    latitude: 20.9958,
    longitude: 105.9510,
    description: "Trạm xe đạp công cộng thông minh phục vụ dạo bộ, tập thể dục quanh bờ cát trắng hồ 24.5ha.",
    sensorIdRef: "S03",
    iconName: "Bike",
  },
  {
    id: "poi-bike-san-ho",
    name: "Trạm mượn xe đạp công cộng - Công viên San Hô",
    category: "bike",
    subdivision: "Phía Nam",
    latitude: 20.9865,
    longitude: 105.9485,
    description: "Trạm mượn xe đạp dạo công viên sinh thái ven sông San Hô.",
    sensorIdRef: "S04",
    iconName: "Bike",
  },
  {
    id: "poi-bike-hai-au",
    name: "Trạm mượn xe đạp công cộng - Quảng trường Hải Âu",
    category: "bike",
    subdivision: "Phía Đông Nam",
    latitude: 20.9938,
    longitude: 105.9592,
    description: "Điểm mượn xe đạp dạo biển hồ nước mặn Crystal Lagoons và khu phố thương mại.",
    sensorIdRef: "S05",
    iconName: "Bike",
  },
  {
    id: "poi-bike-sapphire",
    name: "Trạm mượn xe đạp công cộng - Đại lộ Sapphire",
    category: "bike",
    subdivision: "Phía Tây Bắc",
    latitude: 20.9968,
    longitude: 105.9422,
    description: "Trạm xe đạp nội khu kết nối các cụm sân thể thao và vườn Nhật Sapphire.",
    sensorIdRef: "S02",
    iconName: "Bike",
  },
];
