import {
  AdminDevice,
  DeviceEvent,
  DeviceMutationOutcome,
  DeviceMutationResult,
  DeviceRegistryResponse,
} from "../types";

const now = new Date();
const minutesAgo = (m: number) =>
  new Date(now.getTime() - m * 60 * 1000).toISOString();
const daysAgo = (d: number) =>
  new Date(now.getTime() - d * 24 * 3600 * 1000).toISOString();

// Demo data cho module Thiết bị IoT (P2).
// Chỉ tồn tại trên client cho demo MVP; thay bằng /api/v1/devices khi contract chốt.
// Không chứa MQTT URL, token, credential hay serial đầy đủ.
const DEMO_DEVICES: AdminDevice[] = [
  {
    device_id: "DEV-S01-A",
    device_name: "Cảm biến cổng chính",
    device_type: "PM2.5 sensor (simulator)",
    serial_masked: "SN-****-4471",
    station_id: "S01",
    station_name: "Cổng chính VinUni",
    region_id: "vinuni",
    region_name: "VinUni Campus",
    connectivity: "online",
    connectivity_reason: null,
    last_heartbeat_at: minutesAgo(1),
    heartbeat_interval_seconds: 60,
    uptime_ratio_24h: 0.998,
    latency_ms: 142,
    firmware_version: "1.4.2",
    firmware_recommended: "1.4.2",
    firmware_state: "up_to_date",
    config_profile: "standard-60s",
    config_version: "v7",
    config_checksum: "sha256:9f2c…c41d",
    config_state: "in_sync",
    config_applied_at: daysAgo(9),
    calibration_note: "Hiệu chuẩn gần nhất 12/06/2026 · offset +0.4 µg/m³",
    lifecycle: "active",
    is_simulator: true,
    source: "Simulator",
    provisioned_at: daysAgo(180),
    owner: "AirGuard Operations",
    data_quality: {
      window_label: "24 giờ gần nhất",
      invalid_count: 0,
      duplicate_count: 2,
      rejected_count: 0,
      last_reason_code: "DUPLICATE_TIMESTAMP",
      last_event_at: minutesAgo(220),
    },
    last_event: {
      id: "EVT-S01A-1",
      time: daysAgo(9),
      type: "config_applied",
      detail: "Áp dụng config profile standard-60s (v7)",
      outcome: "SUCCEEDED",
      correlation_id: "req-d-7712",
    },
  },
  {
    device_id: "DEV-S02-A",
    device_name: "Cảm biến bãi đỗ xe",
    device_type: "PM2.5 sensor (simulator)",
    serial_masked: "SN-****-4488",
    station_id: "S02",
    station_name: "Bãi đỗ xe trung tâm",
    region_id: "vinuni",
    region_name: "VinUni Campus",
    connectivity: "stale",
    connectivity_reason:
      "Heartbeat cuối cách đây 95 phút, vượt ngưỡng freshness của backend",
    last_heartbeat_at: minutesAgo(95),
    heartbeat_interval_seconds: 60,
    uptime_ratio_24h: 0.874,
    latency_ms: null,
    firmware_version: "1.3.8",
    firmware_recommended: "1.4.2",
    firmware_state: "update_available",
    config_profile: "standard-60s",
    config_version: "v6",
    config_checksum: "sha256:41ab…9e07",
    config_state: "drift",
    config_applied_at: daysAgo(46),
    calibration_note: "Chưa hiệu chuẩn lại sau khi thay vị trí lắp đặt",
    lifecycle: "active",
    is_simulator: true,
    source: "Simulator",
    provisioned_at: daysAgo(178),
    owner: "AirGuard Operations",
    data_quality: {
      window_label: "24 giờ gần nhất",
      invalid_count: 3,
      duplicate_count: 0,
      rejected_count: 3,
      last_reason_code: "STALE_MEASUREMENT",
      last_event_at: minutesAgo(95),
    },
    last_event: {
      id: "EVT-S02A-1",
      time: minutesAgo(95),
      type: "publish_failure",
      detail: "Publish telemetry thất bại, thiết bị chuyển sang trạng thái stale",
      outcome: "FAILED",
      correlation_id: "req-d-5120",
    },
  },
  {
    device_id: "DEV-S03-A",
    device_name: "Cảm biến trục đường chính",
    device_type: "PM2.5 sensor (simulator)",
    serial_masked: "SN-****-5102",
    station_id: "S03",
    station_name: "Trục đường chính Ocean Park",
    region_id: "ocean-park",
    region_name: "Vinhomes Ocean Park",
    connectivity: "online",
    connectivity_reason: null,
    last_heartbeat_at: minutesAgo(2),
    heartbeat_interval_seconds: 60,
    uptime_ratio_24h: 0.995,
    latency_ms: 178,
    firmware_version: "1.4.2",
    firmware_recommended: "1.4.2",
    firmware_state: "up_to_date",
    config_profile: "traffic-30s",
    config_version: "v7",
    config_checksum: "sha256:7b10…2f55",
    config_state: "in_sync",
    config_applied_at: daysAgo(9),
    calibration_note: null,
    lifecycle: "active",
    is_simulator: true,
    source: "Simulator",
    provisioned_at: daysAgo(150),
    owner: "Vinhomes Facility Team",
    data_quality: {
      window_label: "24 giờ gần nhất",
      invalid_count: 0,
      duplicate_count: 0,
      rejected_count: 0,
      last_reason_code: null,
      last_event_at: null,
    },
    last_event: {
      id: "EVT-S03A-1",
      time: minutesAgo(410),
      type: "reconnect",
      detail: "Thiết bị kết nối lại sau khi broker restart",
      outcome: "SUCCEEDED",
      correlation_id: "req-d-4980",
    },
  },
  {
    device_id: "DEV-S04-A",
    device_name: "Cảm biến công viên trung tâm",
    device_type: "PM2.5 sensor (simulator)",
    serial_masked: "SN-****-5140",
    station_id: "S04",
    station_name: "Công viên trung tâm",
    region_id: "ocean-park",
    region_name: "Vinhomes Ocean Park",
    connectivity: "offline",
    connectivity_reason:
      "Backend không nhận được heartbeat từ 05:40; đội bảo trì đã được thông báo",
    last_heartbeat_at: minutesAgo(340),
    heartbeat_interval_seconds: 60,
    uptime_ratio_24h: 0.62,
    latency_ms: null,
    firmware_version: "1.4.0",
    firmware_recommended: "1.4.2",
    firmware_state: "update_available",
    config_profile: "standard-60s",
    config_version: "v7",
    config_checksum: "sha256:c93e…8a12",
    config_state: "pending",
    config_applied_at: null,
    calibration_note: null,
    lifecycle: "maintenance",
    is_simulator: true,
    source: "Simulator",
    provisioned_at: daysAgo(120),
    owner: "Vinhomes Facility Team",
    data_quality: {
      window_label: "24 giờ gần nhất",
      invalid_count: 0,
      duplicate_count: 0,
      rejected_count: 0,
      last_reason_code: "NO_TELEMETRY",
      last_event_at: minutesAgo(340),
    },
    last_event: {
      id: "EVT-S04A-1",
      time: minutesAgo(340),
      type: "offline",
      detail: "Mất heartbeat; config v7 vẫn ở trạng thái pending chưa áp dụng",
      outcome: "FAILED",
      correlation_id: "req-d-5008",
    },
  },
  {
    device_id: "DEV-S05-A",
    device_name: "Cảm biến khu thể thao",
    device_type: "PM2.5 sensor (simulator)",
    serial_masked: "SN-****-5177",
    station_id: "S05",
    station_name: "Khu thể thao ngoài trời",
    region_id: "ocean-park",
    region_name: "Vinhomes Ocean Park",
    connectivity: "invalid",
    connectivity_reason:
      "Thiết bị vẫn publish nhưng payload không qua validation (PM2.5 âm)",
    last_heartbeat_at: minutesAgo(6),
    heartbeat_interval_seconds: 60,
    uptime_ratio_24h: 0.981,
    latency_ms: 205,
    firmware_version: "1.2.5",
    firmware_recommended: "1.4.2",
    firmware_state: "update_available",
    config_profile: "legacy-120s",
    config_version: "v4",
    config_checksum: "sha256:0d77…31bc",
    config_state: "drift",
    config_applied_at: daysAgo(75),
    calibration_note: "Chưa có calibration metadata từ lần provision đầu tiên",
    lifecycle: "active",
    is_simulator: true,
    source: "Simulator",
    provisioned_at: daysAgo(75),
    owner: "Vinhomes Facility Team",
    data_quality: {
      window_label: "24 giờ gần nhất",
      invalid_count: 47,
      duplicate_count: 1,
      rejected_count: 47,
      last_reason_code: "PM25_OUT_OF_RANGE",
      last_event_at: minutesAgo(6),
    },
    last_event: {
      id: "EVT-S05A-1",
      time: minutesAgo(6),
      type: "invalid_payload",
      detail: "Measurement bị validation từ chối: PM2.5 = -3.2",
      outcome: "REJECTED",
      correlation_id: "req-d-5233",
    },
  },
  {
    device_id: "DEV-SPARE-01",
    device_name: "Thiết bị dự phòng kho",
    device_type: "PM2.5 sensor (simulator)",
    serial_masked: "SN-****-6003",
    station_id: null,
    station_name: null,
    region_id: null,
    region_name: null,
    connectivity: "offline",
    connectivity_reason:
      "Thiết bị chưa gán trạm nên không có telemetry; không suy diễn thành online",
    last_heartbeat_at: null,
    heartbeat_interval_seconds: null,
    uptime_ratio_24h: null,
    latency_ms: null,
    firmware_version: "1.4.2",
    firmware_recommended: "1.4.2",
    firmware_state: "up_to_date",
    config_profile: "unassigned",
    config_version: "—",
    config_checksum: "Chưa áp dụng",
    config_state: "unknown",
    config_applied_at: null,
    calibration_note: null,
    lifecycle: "deactivated",
    is_simulator: true,
    source: "Simulator",
    provisioned_at: daysAgo(20),
    owner: "AirGuard Operations",
    data_quality: {
      window_label: "24 giờ gần nhất",
      invalid_count: 0,
      duplicate_count: 0,
      rejected_count: 0,
      last_reason_code: null,
      last_event_at: null,
    },
    last_event: {
      id: "EVT-SPARE-1",
      time: daysAgo(20),
      type: "provision",
      detail: "Provision vào registry, chưa gán trạm và đang deactivated",
      outcome: "SUCCEEDED",
      correlation_id: "req-d-3001",
    },
  },
];

const DEMO_DEVICE_EVENTS: Record<string, DeviceEvent[]> = {
  "DEV-S01-A": [
    {
      id: "EVT-S01A-1",
      time: daysAgo(9),
      type: "config_applied",
      detail: "Áp dụng config profile standard-60s (v7)",
      outcome: "SUCCEEDED",
      correlation_id: "req-d-7712",
    },
    {
      id: "EVT-S01A-2",
      time: daysAgo(30),
      type: "firmware_update",
      detail: "Cập nhật firmware 1.4.0 -> 1.4.2 qua dispatcher server-side",
      outcome: "SUCCEEDED",
      correlation_id: "req-d-6620",
    },
  ],
  "DEV-S02-A": [
    {
      id: "EVT-S02A-1",
      time: minutesAgo(95),
      type: "publish_failure",
      detail:
        "Publish telemetry thất bại, thiết bị chuyển sang trạng thái stale",
      outcome: "FAILED",
      correlation_id: "req-d-5120",
    },
    {
      id: "EVT-S02A-2",
      time: daysAgo(46),
      type: "config_applied",
      detail: "Áp dụng config v6; rollout v7 chưa được dispatch",
      outcome: "SUCCEEDED",
      correlation_id: "req-d-4410",
    },
  ],
  "DEV-S03-A": [
    {
      id: "EVT-S03A-1",
      time: minutesAgo(410),
      type: "reconnect",
      detail: "Thiết bị kết nối lại sau khi broker restart",
      outcome: "SUCCEEDED",
      correlation_id: "req-d-4980",
    },
  ],
  "DEV-S04-A": [
    {
      id: "EVT-S04A-1",
      time: minutesAgo(340),
      type: "offline",
      detail: "Mất heartbeat; config v7 vẫn ở trạng thái pending chưa áp dụng",
      outcome: "FAILED",
      correlation_id: "req-d-5008",
    },
    {
      id: "EVT-S04A-2",
      time: minutesAgo(360),
      type: "maintenance",
      detail: "Trần Quốc Việt (admin) đặt thiết bị vào chế độ bảo trì",
      outcome: "SUCCEEDED",
      correlation_id: "req-d-4999",
    },
  ],
  "DEV-S05-A": [
    {
      id: "EVT-S05A-1",
      time: minutesAgo(6),
      type: "invalid_payload",
      detail: "Measurement bị validation từ chối: PM2.5 = -3.2",
      outcome: "REJECTED",
      correlation_id: "req-d-5233",
    },
    {
      id: "EVT-S05A-2",
      time: daysAgo(75),
      type: "provision",
      detail: "Provision thiết bị và gán trạm S05",
      outcome: "SUCCEEDED",
      correlation_id: "req-d-2101",
    },
  ],
  "DEV-SPARE-01": [
    {
      id: "EVT-SPARE-1",
      time: daysAgo(20),
      type: "provision",
      detail: "Provision vào registry, chưa gán trạm và đang deactivated",
      outcome: "SUCCEEDED",
      correlation_id: "req-d-3001",
    },
  ],
};

export const deviceRegistryApi = {
  async getDevices(): Promise<DeviceRegistryResponse> {
    const unassigned = DEMO_DEVICES.filter(
      (device) => device.station_id === null,
    );
    return {
      devices: DEMO_DEVICES,
      partial_error: unassigned.length
        ? `${unassigned.length} thiết bị chưa gán trạm nên không có telemetry hoặc heartbeat. Xem lý do trong bảng.`
        : null,
    };
  },

  async getDeviceEvents(deviceId: string): Promise<DeviceEvent[]> {
    return DEMO_DEVICE_EVENTS[deviceId] ?? [];
  },

  /**
   * Mutation lifecycle/cấu hình chưa có endpoint trong MVP.
   * Trả `not_configured` để UI không tuyên bố hành động đã thành công.
   */
  async requestAction(
    deviceId: string,
    action: string,
    _reason: string,
  ): Promise<DeviceMutationResult> {
    const outcome: DeviceMutationOutcome = "not_configured";
    return {
      outcome,
      message: `Chưa có endpoint Admin cho hành động \`${action}\` trên ${deviceId}. Backend phải trả outcome trước khi UI xác nhận kết quả.`,
      audit_entry: null,
    };
  },
};
